# Change these first
owner: hecker-01 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: HeckerDev.net
    url: https://heckerdev.net
    slug: hacker-dev-net
    icon: https://heckerdev.net/favicon.png
  - name: MangaHD.net
    url: https://mangahd.net
    slug: manga-hd-net
    icon: https://mangahd.net/icon.png
  - name: MangaHD Database
    url: https://mangahd.net/api/database-health
    slug: manga-hd-database

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.heckerdev.net
  # baseUrl: /your-repo-name
  favicon: https://heckerdev.net/favicon.png
  logoUrl: https://heckerdev.net/favicon.png
  themeUrl: https://status.heckerdev.net/darkhd.css
  name: HeckerDev Status
  introTitle: "HeckerDev Site Status"
  introMessage: "Live uptime and availability tracking for websites owned by HeckerDev."
  navbar:
    - title: Status
      href: /
    - title: HeckerDev.net
      href: https://status.heckerdev.net/history/hecker-dev-net
    - title: MangaHD.net
      href: https://status.heckerdev.net/history/manga-hd-net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
